from sales_tax.module.item import Item
from sales_tax.module.sales_tax import Order
from sales_tax.module.sales_tax import SalesTax

if __name__ == "__main__":
    item_1 = Item("book", 1, 12.49)
    item_2 = Item("music CD", 1, 14.99)
    item_3 = Item("chocolate bar", 1, 0.85)
    order_1 = Order()
    order_1.set(item_1)
    order_1.set(item_2)
    order_1.set(item_3)
    print("--------Input 1---------")
    sales_tax_order_1 = SalesTax(order_1.item)
    sales_tax_order_1.print_order()
    sales_tax_order_1.calculate_sales_tax()
    print("-----------Output 1------------")
    sales_tax_order_1.print_receipt()

    print("--------Input 2---------")
    item_4 = Item("imported box of chocolates", 1, 10.00)
    item_5 = Item("imported bottle of perfume", 1, 47.50)
    order_2 = Order()
    order_2.set(item_4)
    order_2.set(item_5)
    sales_tax_order_2 = SalesTax(order_2.item)
    sales_tax_order_2.print_order()
    sales_tax_order_2.calculate_sales_tax()
    print("-----------Output 2------------")
    sales_tax_order_2.print_receipt()

    # print("--------Input 3---------")
    item_6 = Item("imported bottle of perfume", 1, 27.99)
    item_7 = Item("bottle of perfume", 1, 18.99)
    item_8 = Item("packet of headache pills", 1, 9.75)
    item_9 = Item("box of imported chocolates", 1, 11.25)
    order_3 = Order()
    order_3.set(item_6)
    order_3.set(item_7)
    order_3.set(item_8)
    order_3.set(item_9)
    sales_tax_order_3 = SalesTax(order_3.item)
    sales_tax_order_3.print_order()
    sales_tax_order_3.calculate_sales_tax()
    print("-----------Output 3------------")
    sales_tax_order_3.print_receipt()
